### PR TITLE
Modified Set Siren to use AudioAlarmPlay

### PR DESCRIPTION
**Pull request by ptyers**
Before merging we need to wait on results of tests I have asked for.
#reolink_dev/293

Unknowns
1. Is there a V20 version of AudioAlarmPlay ????
2. Is there interaction with an unknown API which sets Audio Volume

[Test Results - .zip](https://github.com/fwestenberg/reolink/files/7665388/Test.Results.-.zip)

### CODE REVIEW

**Comment by ptyers** [comment]
The only unknown now I believe is if there is an unknown set audio level API.
Documentation just to hand indicates no V20 version of AudioAlarmPlay.

tests returned for E1 Zoom, DUO, 811 indicate siren code does what is expected on those cameras

I have made minor adjustment to WhiteLed to get around an up till now unknown sensitivity to turning off it motion seen then motion not seen.

**Comment by ptyers** [comment]
Found circumstance where spotlight would not turn off. Camera now reverts to Night Mode, Auto when spotlight turns off. Schedule still left as 0000 to 235
Latest Test results appended

[Test Results -  (2).zip](https://github.com/fwestenberg/reolink/files/7673981/Test.Results.-.2.zip)
9.

**Comment by cpainchaud** [comment]
@ptyers is that PR ready now?

**Comment by ptyers** [comment]
Your Call.
Have not been able to ascertain if there exists an API which modifiers alarm volume as yet.
If it exists there will need be minor and I stress minor changes necessary to set_alarm routine in reolink module but they will not be urgent and could be incorporated as adjunct to other PR's.

The tests returned by other camera users seem to indicate no problems with the scripts I sent them and which have been incorporated in the PR.

Tests on my Reolink DUO appear to do all the right things. No immediate changes will be needed to reolink_dev except of course updating the release number of reolink module.

I'd be willing to say its ready

**Comment by cpainchaud** [comment]
Ok, I was under the impression you were still making investigations.

**Pull request merged**
