### PR TITLE
Support setting the channel

### PR DESCRIPTION
**Pull request by Bre77**
For use with NVR's, allow this API to connect to a different channel.

### CODE REVIEW

**Comment by fwestenberg** [comment]
Hi, perhaps you didn't notice the options menu, at the integrations page. It calls `async def update_streaming_options` to set the channel.

IMG_20201210_071358

**Comment by Bre77** [comment]
Right, I didn't see the update_streaming_options function in my review. I would still suggest adding this to the library to enable setting this value upfront. It may help solve the issue you have with Unique ID's in Home Assistant.

**Comment by fwestenberg** [comment]
The library you mean at the moment you add the camera right? I'll save this for the moment I'll start reworking the whole NVR part.
For NVR it should create multiple camera's etc, so a lot of (performance) improvements can be done here.

**Comment by fwestenberg** [comment]
I fixed this, and some other things. The new HACS version will be released soon!

**Pull request closed without merging**
